# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ramen < Formula
  desc "A graphic CLI for interaction with Ethereum easily and happily."
  homepage ""
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dyng/ramen/releases/download/v0.2.0/ramen_Darwin_arm64.tar.gz"
      sha256 "d00a47d39c33e617d248b85319000234c17036f8800fb1f340f3f3deb51e9122"

      def install
        bin.install "ramen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dyng/ramen/releases/download/v0.2.0/ramen_Darwin_x86_64.tar.gz"
      sha256 "0abb2b9ba985fbae61db608b450fa8aa0b086f88b03c9a757313f0afc506276f"

      def install
        bin.install "ramen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dyng/ramen/releases/download/v0.2.0/ramen_Linux_arm64.tar.gz"
      sha256 "d48b775f102c5efbf7b6d6141a345673f1489c86f730d6f6d1820cabc3388531"

      def install
        bin.install "ramen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dyng/ramen/releases/download/v0.2.0/ramen_Linux_x86_64.tar.gz"
      sha256 "925d9c93acc0b7736ee51434966ff735ada2551ec35d74bbbce70ba2bdaaf341"

      def install
        bin.install "ramen"
      end
    end
  end

  test do
    system "ramen version"
  end
end
