# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ramen < Formula
  desc "A graphic CLI for interaction with Ethereum easily and happily."
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dyng/ramen/releases/download/v0.1.0/ramen_Darwin_arm64.tar.gz"
      sha256 "14587c7709498d72c450f4ad743fb7fede247b5dec62b7c17cbbb412b399395b"

      def install
        bin.install "ramen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dyng/ramen/releases/download/v0.1.0/ramen_Darwin_x86_64.tar.gz"
      sha256 "127027385f4f6deb76595efe84a0dda587b0493530f071cc47fe50d947876001"

      def install
        bin.install "ramen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dyng/ramen/releases/download/v0.1.0/ramen_Linux_arm64.tar.gz"
      sha256 "00a9e65352fa8182343637ff6fb4b4f5b6124a55788b2c01f7e66caf317842ea"

      def install
        bin.install "ramen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dyng/ramen/releases/download/v0.1.0/ramen_Linux_x86_64.tar.gz"
      sha256 "7cc28190427f10c0c801b352360d3dfe5340775a05db52b154869272497d4384"

      def install
        bin.install "ramen"
      end
    end
  end

  test do
    system "ramen version"
  end
end
