# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ramen < Formula
  desc "A graphic CLI for interaction with Ethereum easily and happily."
  homepage ""
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dyng/ramen/releases/download/v0.1.1/ramen_Darwin_arm64.tar.gz"
      sha256 "2ec0e2feb13373ea7676c1e045b39092dbc6293eee909b1c84ec82b2dd9823af"

      def install
        bin.install "ramen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dyng/ramen/releases/download/v0.1.1/ramen_Darwin_x86_64.tar.gz"
      sha256 "229b3fb6c81d81239c2d3e6e02aa910780e05271efdb4b79b9fd75053156bf13"

      def install
        bin.install "ramen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dyng/ramen/releases/download/v0.1.1/ramen_Linux_arm64.tar.gz"
      sha256 "b9da0aa09dfff89cefbc28b232e9dfb5d5564f1493c4eae745adaa1a5a329066"

      def install
        bin.install "ramen"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dyng/ramen/releases/download/v0.1.1/ramen_Linux_x86_64.tar.gz"
      sha256 "90c19c785881bd77e6113923ad52788c4ed7e16a06b14da3306244654737605d"

      def install
        bin.install "ramen"
      end
    end
  end

  test do
    system "ramen version"
  end
end
